### ISSUE TITLE
Upgrade manual fix for `darwinia-v0.12.4` branch

### ISSUE THREAD

**Issue by boundless-forest** [darwinia-network/frontier#11]
Waiting for substrate upgrade to contain https://github.com/paritytech/substrate/pull/10662 and https://github.com/paritytech/substrate/pull/10403

**Comment by acgxv** [comment]
@AsceticBear, what's the state of this?

**Comment by boundless-forest** [comment]
I have hacked the darwinia-frontier branches to adapt our demand, Close it.
